name: Run Selenium Java Cucumber Tests

on:
  push:
    branches:
      - master  # Trigger this workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the environment where the workflow will run

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 11 (using Temurin JDK)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'  # Specify JDK 11
        distribution: 'temurin'  # Temurin is the distribution (use 'openjdk' if needed)

    # Step 3: Cache Maven dependencies to speed up builds (optional)
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Check Java syntax by compiling the code
    - name: Check Java syntax
      run: mvn compile
      working-directory: ./new-se-ja-cu  # Adjust if your pom.xml is in a different directory

    # Step 5: Run Selenium tests in headless mode
    - name: Run Selenium tests in headless mode
      run: mvn test -Dselenium.headless=true
      working-directory: ./new-se-ja-cu  # Adjust if your pom.xml is in a different directory
